baseURL = 'https://gvn22.github.io'
relativeURLs = true
canonifyURLs = true
languageCode = 'en-uk'
title = 'Girish Nivarti'
theme = 'bwlp'

[Author]
  name = "Girish Nivarti"
  title = "Research Scientist"

[params]

  [[params.links]]
      iconset = "fas"
      icon = "envelope"
      title = "E-mail"
      url = "mailto:g.v.nivarti@leeds.ac.uk"

  [[params.links]]
      iconset = "ai"
      iconorigin = "ai"
      icon = "researchgate-square"
      title = "researchgate"
      url = "https://www.researchgate.net/profile/Girish-Nivarti"

  [[params.links]]
      icon = "github"
      title = "Github"
      url = "https://github.com/gvn22"

  [[params.links]]
      icon = "linkedin"
      title = "Linked-in"
      url = "https://uk.linkedin.com/in/girish-nivarti-phd"
